import type { AppIconName } from '@/components/ui/app-icon';

/** Legacy Ionicons names still used in `icon` props — mapped to Material Community Icons. */
const IONICON_TO_APP_ICON = {
  'add': 'plus',
  'add-circle-outline': 'plus-circle-outline',
  'airplane': 'quadcopter',
  'airplane-outline': 'quadcopter',
  'alert-circle': 'alert-circle-outline',
  'analytics-outline': 'chart-line',
  'arrow-back': 'arrow-left',
  'basket-outline': 'basket-outline',
  'briefcase-outline': 'briefcase-outline',
  'bug-outline': 'bug-outline',
  'calendar-outline': 'calendar-month-outline',
  'call-outline': 'phone-outline',
  'card-outline': 'credit-card-outline',
  'cash-outline': 'bank-outline',
  'chatbox-ellipses-outline': 'message-text-outline',
  'chatbubbles-outline': 'chat-outline',
  'checkmark': 'check',
  'checkmark-circle': 'check-circle',
  'chevron-back': 'chevron-left',
  'chevron-down': 'chevron-down',
  'chevron-forward': 'chevron-right',
  'close': 'close',
  'create-outline': 'pencil-outline',
  'close-circle': 'close-circle',
  'cloud-outline': 'weather-cloudy',
  'cube-outline': 'warehouse',
  'document-text': 'file-document-outline',
  'document-text-outline': 'file-document-outline',
  'earth-outline': 'earth',
  'ellipsis-horizontal-outline': 'dots-horizontal',
  'ellipse': 'circle-small',
  'ellipse-outline': 'circle-outline',
  'flask-outline': 'flask-outline',
  'flash-outline': 'flash-outline',
  'flag-outline': 'flag-outline',
  'grid-outline': 'view-grid-outline',
  'home': 'home-variant',
  'information-circle-outline': 'information-outline',
  'layers-outline': 'layers-outline',
  'leaf-outline': 'sprout-outline',
  'list-outline': 'format-list-bulleted',
  'location-outline': 'map-marker-outline',
  'lock-closed-outline': 'lock-outline',
  'mail-outline': 'email-outline',
  'map-outline': 'map-marker-outline',
  'mic': 'microphone',
  'navigate-outline': 'navigation-variant-outline',
  'nutrition-outline': 'barley',
  'person': 'account',
  'person-circle-outline': 'account-circle-outline',
  'person-outline': 'account-outline',
  'pin-outline': 'map-marker-outline',
  'pulse-outline': 'chart-timeline-variant',
  'rainy-outline': 'weather-rainy',
  'resize-outline': 'resize',
  'ribbon-outline': 'medal-outline',
  'rose-outline': 'fruit-cherries',
  'scale-outline': 'scale-balance',
  'scan-outline': 'barcode-scan',
  'school-outline': 'school-outline',
  'search-outline': 'magnify',
  'seed-outline': 'seed-outline',
  'send': 'send',
  'shield-checkmark-outline': 'shield-check-outline',
  'snow-outline': 'snowflake',
  'sparkles-outline': 'auto-fix',
  'stop': 'stop',
  'sunny-outline': 'weather-sunny',
  'text-outline': 'format-text',
  'thermometer-outline': 'thermometer',
  'time-outline': 'clock-outline',
  'trash-outline': 'delete-outline',
  'trending-down-outline': 'trending-down',
  'trending-up-outline': 'trending-up',
  'wallet-outline': 'wallet-outline',
  'water-outline': 'water',
} as const satisfies Record<string, AppIconName>;

export type LegacyIconName = keyof typeof IONICON_TO_APP_ICON;

export type IconName = AppIconName | LegacyIconName;

export function resolveAppIcon(name: IconName): AppIconName {
  if (name in IONICON_TO_APP_ICON) {
    return IONICON_TO_APP_ICON[name as LegacyIconName];
  }
  return name as AppIconName;
}
