import AsyncStorage from '@react-native-async-storage/async-storage';
import * as Clipboard from 'expo-clipboard';
import { File, Directory, Paths } from 'expo-file-system';
import * as LegacyFS from 'expo-file-system/legacy';
import * as Print from 'expo-print';
import { Alert, Linking, Platform, Share } from 'react-native';

import { receiptPublicService } from '@/services/receipt-public.service';

const ANDROID_DOWNLOADS_DIR_KEY = 'krishimotto:android-downloads-saf-uri';

export type TrustDeedPdfInput = {
  qrId: string;
  publicReceiptUrl: string;
  warehouseName?: string;
  cropType?: string;
  depositorName?: string;
  contractNumber?: string;
  receiptId?: string;
  quantityKg?: number;
  valuationLabel?: string;
};

export type TrustDeedDownloadResult = {
  location: 'downloads' | 'documents';
  fileUri?: string;
};

function pdfFilename(qrId: string): string {
  return `trust-deed-${qrId}.pdf`;
}

function pdfBasename(qrId: string): string {
  return `trust-deed-${qrId}`;
}

function qrImageUrl(data: string, size = 220): string {
  return `https://api.qrserver.com/v1/create-qr-code/?size=${size}x${size}&data=${encodeURIComponent(data)}`;
}

function esc(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

export function buildTrustDeedPdfHtml(input: TrustDeedPdfInput): string {
  const rows: Array<[string, string]> = [
    ['Verification ID', input.qrId],
    ['Public URL', input.publicReceiptUrl],
  ];

  if (input.contractNumber) rows.push(['Receipt number', input.contractNumber]);
  if (input.receiptId) rows.push(['On-chain ID', input.receiptId]);
  if (input.warehouseName) rows.push(['Warehouse', input.warehouseName]);
  if (input.cropType) rows.push(['Crop', input.cropType]);
  if (input.depositorName) rows.push(['Depositor', input.depositorName]);
  if (input.quantityKg != null) {
    rows.push(['Quantity', `${input.quantityKg.toLocaleString('en-IN')} kg`]);
  }
  if (input.valuationLabel) rows.push(['Valuation', input.valuationLabel]);

  const detailRows = rows
    .map(
      ([label, value]) =>
        `<tr><td style="padding:8px 12px;color:#64748b;font-size:12px;width:38%;vertical-align:top;">${esc(label)}</td><td style="padding:8px 12px;color:#1A365D;font-size:13px;font-weight:600;word-break:break-all;">${esc(value)}</td></tr>`,
    )
    .join('');

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Trust Deed ${esc(input.qrId)}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 0; padding: 32px; color: #1A365D; background: #fff; }
    .header { background: linear-gradient(135deg, #0a2e24, #134a3a); color: #fff; border-radius: 16px; padding: 24px; margin-bottom: 24px; }
    .eyebrow { color: #d4af37; font-size: 10px; letter-spacing: 0.12em; text-transform: uppercase; font-weight: 700; }
    h1 { margin: 8px 0 0; font-size: 24px; }
    .subtitle { margin-top: 6px; color: rgba(255,255,255,0.85); font-size: 14px; }
    .card { border: 1px solid #e2e8f0; border-radius: 16px; padding: 20px; margin-bottom: 20px; }
    table { width: 100%; border-collapse: collapse; }
    tr + tr td { border-top: 1px solid #f1f5f9; }
    .footer { margin-top: 24px; font-size: 11px; color: #64748b; text-align: center; }
  </style>
</head>
<body>
  <div class="header">
    <div class="eyebrow">KrishiAadhar · Sovereign Crop Trust</div>
    <h1>Warehouse Trust Deed</h1>
    <div class="subtitle">Scan the QR code or open the verification URL to confirm this stored crop record.</div>
  </div>
  <div class="card" style="text-align:center;">
    <img src="${qrImageUrl(input.publicReceiptUrl)}" width="220" height="220" alt="Trust deed QR" />
    <div style="margin-top:12px;font-family:monospace;font-size:14px;font-weight:700;">${esc(input.qrId)}</div>
  </div>
  <div class="card">
    <table>${detailRows}</table>
  </div>
  <div class="footer">Generated by KrishiMotto · ${esc(new Date().toLocaleString('en-IN'))}</div>
</body>
</html>`;
}

async function getAndroidDownloadsDirectoryUri(): Promise<string | null> {
  const cached = await AsyncStorage.getItem(ANDROID_DOWNLOADS_DIR_KEY);
  if (cached) {
    return cached;
  }

  const initialUri = LegacyFS.StorageAccessFramework.getUriForDirectoryInRoot('Download');
  const permissions =
    await LegacyFS.StorageAccessFramework.requestDirectoryPermissionsAsync(initialUri);

  if (!permissions.granted || !permissions.directoryUri) {
    return null;
  }

  await AsyncStorage.setItem(ANDROID_DOWNLOADS_DIR_KEY, permissions.directoryUri);
  return permissions.directoryUri;
}

async function savePdfToAndroidDownloads(tempUri: string, qrId: string): Promise<boolean> {
  const directoryUri = await getAndroidDownloadsDirectoryUri();
  if (!directoryUri) {
    return false;
  }

  const base64 = await LegacyFS.readAsStringAsync(tempUri, {
    encoding: LegacyFS.EncodingType.Base64,
  });

  const fileUri = await LegacyFS.StorageAccessFramework.createFileAsync(
    directoryUri,
    pdfBasename(qrId),
    'application/pdf',
  );

  await LegacyFS.writeAsStringAsync(fileUri, base64, {
    encoding: LegacyFS.EncodingType.Base64,
  });

  return true;
}

async function savePdfToAppDocuments(tempUri: string, qrId: string): Promise<string> {
  const receiptsDir = new Directory(Paths.document, 'receipts');
  receiptsDir.create({ idempotent: true });

  const destFile = new File(receiptsDir, pdfFilename(qrId));
  if (destFile.exists) {
    destFile.delete();
  }

  const sourceFile = new File(tempUri);
  sourceFile.copy(destFile);
  return destFile.uri;
}

async function savePdfToWebDownloads(tempUri: string, qrId: string): Promise<void> {
  const response = await fetch(tempUri);
  const blob = await response.blob();
  const objectUrl = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = objectUrl;
  anchor.download = pdfFilename(qrId);
  anchor.click();
  URL.revokeObjectURL(objectUrl);
}

export async function openTrustDeedUrl(url: string): Promise<void> {
  await Linking.openURL(url);
}

export async function copyTrustDeedUrl(url: string): Promise<void> {
  await Clipboard.setStringAsync(url);
}

export async function shareTrustDeedUrl(url: string, title: string): Promise<void> {
  await Share.share({
    title,
    message: Platform.OS === 'android' ? `${title}\n${url}` : title,
    url: Platform.OS === 'ios' ? url : undefined,
  });
}

export async function downloadTrustDeedPdf(input: TrustDeedPdfInput): Promise<TrustDeedDownloadResult> {
  let enriched = input;

  try {
    const { data } = await receiptPublicService.get(input.qrId);
    const receipt = data.data;
    enriched = {
      ...input,
      warehouseName: receipt.warehouse.name,
      cropType: receipt.commodity.cropType,
      depositorName: receipt.depositor.name,
      contractNumber: receipt.smartContract?.contractNumber ?? input.contractNumber,
      receiptId: receipt.smartContract?.receiptId ?? input.receiptId,
      quantityKg:
        receipt.commodity.measuredWeightQtl > 0
          ? Math.round(receipt.commodity.measuredWeightQtl * 100)
          : input.quantityKg,
    };
  } catch {
    // Fall back to fields already on the client.
  }

  const html = buildTrustDeedPdfHtml(enriched);
  const { uri } = await Print.printToFileAsync({ html });

  if (Platform.OS === 'web') {
    await savePdfToWebDownloads(uri, input.qrId);
    return { location: 'downloads' };
  }

  if (Platform.OS === 'android') {
    const savedToDownloads = await savePdfToAndroidDownloads(uri, input.qrId);
    if (savedToDownloads) {
      return { location: 'downloads' };
    }

    const fileUri = await savePdfToAppDocuments(uri, input.qrId);
    return { location: 'documents', fileUri };
  }

  const fileUri = await savePdfToAppDocuments(uri, input.qrId);
  return { location: 'documents', fileUri };
}

export function showTrustDeedDownloadAlert(
  result: TrustDeedDownloadResult,
  t: (key: string) => string,
): void {
  if (result.location === 'downloads') {
    Alert.alert(
      t('smartContracts.trustDeedDownloadSuccessTitle'),
      t('smartContracts.trustDeedDownloadSuccessDownloads'),
    );
    return;
  }

  Alert.alert(
    t('smartContracts.trustDeedDownloadSuccessTitle'),
    t('smartContracts.trustDeedDownloadSuccessDocuments'),
  );
}

export function showTrustDeedDownloadErrorAlert(t: (key: string) => string): void {
  Alert.alert(
    t('smartContracts.trustDeedDownloadErrorTitle'),
    t('smartContracts.trustDeedDownloadError'),
  );
}
